time|level|timeoffset|message|location
071515_153043.601|INFO|000.000481| Software version: Plus-2.3.0.4217 - Linux| in vtkPlusLogger(183)
071515_153043.601|INFO|000.000566| Logging at level 3 (INFO) to file: /home/snr/Support/Plus-build-codeblocks/bin/Output/071515_153043_PlusLog.txt| in /home/snr/Support/Plus-build-codeblocks/PlusLib/src/PlusServer/Testing/PlusServer.cxx(85)
071515_153043.604|ERROR|000.002837| Failed to open port: unknown - Error opening serial connection| in /home/snr/Support/Plus-build-codeblocks/PlusLib/src/DataCollection/PolarisTracking/vtkNDITracker.cxx(228)
071515_153043.604|ERROR|000.002876| TrackerDevice: Cannot connect to data source, ConnectInternal failed| in /home/snr/Support/Plus-build-codeblocks/PlusLib/src/DataCollection/vtkPlusDevice.cxx(960)
071515_153043.604|ERROR|000.002894| Unable to connect device: TrackerDevice.| in /home/snr/Support/Plus-build-codeblocks/PlusLib/src/DataCollection/vtkDataCollector.cxx(306)
071515_153043.604|ERROR|000.002967| Datacollector failed to connect to devices| in /home/snr/Support/Plus-build-codeblocks/PlusLib/src/PlusServer/Testing/PlusServer.cxx(132)
